services:
  app:
    container_name: app
    build: .
    ports:
     - "8080:80"
    volumes:
     - ./html:/var/www/html
    depends_on:
     - db_prod
    environment:
      DB_USER: user
      DB_PASS: pass
      DB_PROD_HOST: db_prod
      DB_TEST_HOST: db_test
      DB_PROD_NAME: prod
      DB_TEST_NAME: test
    networks:
     - inft2201_network
    
  db_prod:
    image: postgres:18-bookworm
    container_name: postgres-db 
    environment:
      POSTGRES_DB: prod 
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: pass 
    ports:
     - "5432:5432" 
    volumes: 
     - ./init-prod:/docker-entrypoint-initdb.d 
    networks:
     - inft2201_network 

  db_test:
    image: postgres:18-bookworm
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    networks:
      - inft2201_network

networks:
  inft2201_network:
    driver: bridge
    name: inft2201_network
